# call AWS CloudFormation delete
# 2020/09/15 IBM K.Ishikura
#
---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: launch ansible cloudformation delete example
    action: cloudformation
      stack_name="ansible-cloudformation"
      state=absent
      region=us-east-2
      disable_rollback=yes
    args:
      tags:
        Stack: ansible-cloudformation
